import { Page, expect } from '@playwright/test';

import { getTestConfig } from '../config/test-config.ts';
import { runTest, TestContext } from '../helpers/index.ts';
import { escapeUserGuide } from '../components/index.ts';

test('should do an action', async () => {
  console.log('🚀 Starting test...');
  
  await runTest(
    'Do an action', 
    prepareFn,
    testFn,
    getTestConfig({
      instructorLogin: {
        env: 'poc',
        email: 'ducdm@gotitapp.co',
        password: 'GotIt123'
      }
    })
  );
  
  console.log('🎉 Test completed successfully!');
});


async function prepareFn(ctx: TestContext) {
  // prepareFn is optional, so we can skip it
}

async function testFn({ instructorPage }: TestContext) {
  // Your test steps will be generated by recorder-studio
}