import { Page, expect } from '@playwright/test';

import { runTest, escapeUserGuide, TestContext } from '../helpers/playwrightUtils.ts';
import { getTestConfig } from '../config/test-config.ts';

test('should do an action', async () => {
  console.log('🚀 Starting test...');
  
  await runTest(
    'Do an action', 
    testFn,
    getTestConfig({
      instructorLogin: {
        env: 'poc',
        email: 'ducdm@gotitapp.co',
        password: 'GotIt123'
      }
    })
  );
  
  console.log('🎉 Test completed successfully!');
});


async function testFn({ instructorPage }: TestContext) {
  // Your test steps will be generated by recorder-studio
}